# 项目相关配置
ecmpbase:
  # 名称
  name: 企业公车管理平台-微服务层
  # 版本
  version: 1.0.0
  #API url头部前缀
  apiUrlHeader:
  # 版权年份
  copyrightYear: 2019
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: /ecmp/file/upload
  # 获取ip地址开关
  addressEnabled: true

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: config/i18n/messages
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
# 日志配置
logging:
  level:
    com.hq: debug
    org.springframework: warn

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.hq.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:/config/mybatis/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:config/mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 代码生成
gen:
  # 作者,向ruoyi 致敬
  author: hqer
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.hq.demo
  # 自动去除表前缀，默认是true
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: ecmp_
