# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # 主库数据源
            master:
                url: jdbc:mysql://10.7.106.65:3306/ecmp?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
                username: root
                password: hqzc@2019
            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: true
                url: jdbc:mysql://10.7.106.66:3306/ecmp?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
                username: root
                password: hqzc@2019
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter:
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username:
                login-password:
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
    redis:
        cluster:
            nodes: 10.7.106.64:6379,10.7.106.64:6380,10.7.106.65:6379,10.7.106.65:6380,10.7.106.66:6379,10.7.106.66:6380
            max-redirects: 5
            timeout: 6000ms
        lettuce:
            pool:
                max-active: 8
                max-wait: -1ms
                max-idle: 8
                min-idle: 0
#        database: 0
#        password: qBa39fA&?@-o

# 开发环境配置
server:
    # 服务器的HTTP端口，默认为8080
    port: 33000
    servlet:
        # 应用的访问路径
        context-path: /
    tomcat:
        # tomcat的URI编码
        uri-encoding: UTF-8
        # tomcat最大线程数，默认为200
        max-threads: 800
        # Tomcat启动初始化的线程数，默认值25
        min-spare-threads: 30

# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌秘钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    expireTime: 43200
thirdService:
    enterpriseId: 100000
    licenseContent: AAAAAAAA
    apiUrl: http://10.7.106.64:51002

#行程分享路径
order:
   shareUrl: https://www.baidu.com?

file:
  config:
    savepath: d://
  path:
    feedback: /feedback
  url:
    feedback: http://10.117.1.231
#/upload
app:
  zimg:
    server: http://10.117.1.232:4869
    access:
      url: http://123.127.89.218:4869/
  welcome: http://10.117.1.232:4869/a866e23b46c351da88e87ede49bce0de
  background: http://10.117.1.232:4869/a866e23b46c351da88e87ede49bce0de


dispatch:
    #不回车队驻地缓冲时间: 60分钟
    notBackCarGroup: 60
    #回车队驻地缓冲时间: 90分钟
    backCarGroup: 90
    #无车驳回的可操作最小时间限制 30分钟
    noCarDeniedMinutes: 30

#调度行程确认的时间间隔
schedule:
    confirmTimeout: 12

#应用ID
appId: "wxb1c50ac4effd77c7"
#公众号 APP_SECRET
appSecret: "bb9dbc446e5c8bfef07babe402d9d7af"
#商户号
mchId: "1517977791"
#商户秘钥
mchKey: "f6ad7e4369c963d75c2e19a5f88a261a"
#正式环境回调地址
#notify_url: "https://app-api.hqzhixing.com/pay/wechat/v1/callback"
#测试环境回调地址
notify_url: "https://test-app-api.hqzhixing.com:60001/pay/wechat/v1/callback"
#交易类型
trade_type: "APP"
#签名类型
sign_type: "MD5"
